name: Dart linter

on:
  pull_request:
    paths: 
      - 'mobile_app/**'
    branches: [master]
  push:
    paths: 
      - 'mobile_app/**'
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "mobile_app/"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.7.1

      - name: Install dependencies
        run: flutter pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze dart 
        uses: invertase/github-action-dart-analyzer@v1
        with: 
          fatal-infos: false
          fatal-warnings: false
          annotate: true
          annotate-only: false
          working-directory: mobile_app/
