name: Flutter tests

on:
  pull_request:
    paths: 
      - 'mobile_app/**'
    branches: [master]
  push:
    paths: 
      - 'mobile_app/**'
    branches: [master]

jobs:
  flutter-action:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "mobile_app/"
    steps:
      - uses: actions/checkout@v3

      - name: Set up java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.7.1

      - name: Install dependencies
        run: flutter pub get

      - name: Run widget tests
        run: flutter test . 